"""Debug script to see the raw JSON generated by the NLP model."""

import json
from src.nlp import OllamaNLPProcessor, NLPModelType

# Leer el problema
with open("ejemplos/nlp/problema_complejo_reformulado.txt", "r", encoding="utf-8") as f:
    problem_text = f.read()

# Crear procesador
processor = OllamaNLPProcessor(model_type=NLPModelType.LLAMA3_1_8B)

# Procesar
result = processor.process_text(problem_text)

if result.success and result.problem:
    prob = result.problem
    print("=" * 60)
    print("VARIABLES EXTRAÍDAS:")
    print(f"Total: {len(prob.objective_coefficients)}")
    print(f"Nombres: {prob.variable_names}")
    print(f"Coeficientes objetivo: {prob.objective_coefficients}")
    print()
    print("RESTRICCIONES EXTRAÍDAS:")
    for i, constraint in enumerate(prob.constraints):
        coeffs = constraint["coefficients"]
        print(f"\nRestriction {i}:")
        print(f"  Coeficientes ({len(coeffs)}): {coeffs}")
        print(f"  Operador: {constraint['operator']}")
        print(f"  RHS: {constraint['rhs']}")
    print("=" * 60)
else:
    print(f"ERROR: {result.error_message}")
